group: gecturk
task: gecturk_generation
dataset_path: mcemilg/GECTurk-generation
training_split: train
validation_split: validation
test_split: test
output_type: generate_until
doc_to_text: "Verilen cumlenin yazım hatalarını duzeltin.\nHatalı Cümle: {{source}}\nDüzeltilmiş hali: "
doc_to_target: "{{target}}"
generation_kwargs:
  until:
    - "\n"
  do_sample: false
  temperature: 0.0
filter_list:
  - name: "regex_filter_applies_strip_internally"
    filter:
      - function: "regex"
        regex_pattern: ".*"
      - function: "take_first"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: 0.0